### ISSUE TITLE
ENOENT: no such file or directory, open '/usr/local/lib/node_modules/falak/node_modules/@flk/config/package.json'

### ISSUE THREAD

**Issue by devahmedshendy** [falakjs/Falak#2]
Hi, 

I tried to install falak framework to try it and give chance to be contribute to the project.

I tried to figure out why this happening and maybe I can solve it, but I reached some point where I think I wanna ask how/where I can solve this if I get it right.

This command failed when I tried to create new blog using `flk` command:
```
$ flk new blog 
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/falak/node_modules/@flk/config/package.json'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at FileSystem.get (/usr/local/lib/node_modules/falak/node_modules/@flk/fs/src/fs.js:46:23)
    at FileSystem.jsonFile (/usr/local/lib/node_modules/falak/node_modules/@flk/fs/src/fs.js:23:28)
    at FileSystem.getJson (/usr/local/lib/node_modules/falak/node_modules/@flk/fs/src/fs.js:37:21)
    at collectPackageDependencies (/usr/local/lib/node_modules/falak/framework/build/builders/npm-manager.js:58:30)
    at /usr/local/lib/node_modules/falak/framework/build/builders/npm-manager.js:49:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:38929) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38929) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

In `installPackages()` function of `npm-manager.js`, I found that `NODE_MODULES_DIR` value is `/usr/local/lib/node_modules/falak/node_modules/`
```
let packagePath = NODE_MODULES_DIR + '/' + $package;
```

And I found it installed all `falak` dependencies packages successfully, even `@flk/config`, but for each package in the previous dependencies you get its dependencies using `collectPackageDependencies()` function, so for `@flk/config` it is going to read its `package.json` from  '/usr/local/lib/node_modules/falak/node_modules/@flk/config/`.

So using the error stack trace, I found that `@flk/config` wasn't installed at all in `/usr/local/lib/node_modules/falak/node_modules/` in the beginning.
```
$ tree -L 1 /usr/local/lib/node_modules/falak/node_modules/@flk/
/usr/local/lib/node_modules/falak/node_modules/@flk/
├── commander
├── fs
├── parser
├── support-helpers
├── support-javascript
└── supportive-is

6 directories, 0 files
```

All `falak` dependencies here are installed successfully for the local package.
```
$ tree -L 1 blog/node_modules/@flk/
blog/node_modules/@flk/
├── application
├── bootstrap
├── cache
├── commander
├── config
├── crypto
├── dependency-injection
├── endpoint
├── endpoint-service
├── events
├── form
├── fs
├── http
├── layout
├── locale
├── mdbootstrap
├── meta
├── parser
├── random
├── router
├── scss
├── support-helpers
├── support-javascript
├── supportive-is
└── user

25 directories, 0 files
```

Here is the full output of installing `falak` package
```
$ npm install -g falak
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/flk -> /usr/local/lib/node_modules/falak/framework/bin/flk

> node-sass@4.13.0 install /usr/local/lib/node_modules/falak/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/darwin-x64-72_binding.node
Download complete  ⸩ ⠋ :
Binary saved to /usr/local/lib/node_modules/falak/node_modules/node-sass/vendor/darwin-x64-72/binding.node
Caching binary to /Users/ahmed/.npm/node-sass/4.13.0/darwin-x64-72_binding.node

> core-js@2.6.11 postinstall /usr/local/lib/node_modules/falak/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> node-sass@4.13.0 postinstall /usr/local/lib/node_modules/falak/node_modules/node-sass
> node scripts/build.js

Binary found at /usr/local/lib/node_modules/falak/node_modules/node-sass/vendor/darwin-x64-72/binding.node
Testing binary
Binary is fine
+ falak@0.2.7
added 510 packages from 287 contributors in 78.08s
```

Here is my **node** and **npm** versions
```
$ node --version
v12.14.0
$ npm --version
6.13.4
```

I tried installing it using `sudo` command but same result. Also I didn't true this way because I needed guidance to know what exactly `-unsafe-perm=true --allow-root` does, maybe I can know, but didn't spend time on them.
```
npm install -g falak -unsafe-perm=true --allow-root
```

Finally, I am using **Linux based OS**.

**Comment by devahmedshendy** [comment]
@hassanzohdy , Thought tagging you maybe you didn't get notification about this.

**Comment by hassanzohdy** [comment]
Thanks for tagging me in the issue, i didn't notice it lol.
 
The issue i think was some packages needed to be updated, try now reinstalling `Falak` one more time and tell me if it worked with you.

**P.S** almost all packages version now are 1.3.0, so make sure you're getting that version.

**Comment by devahmedshendy** [comment]
Lol it's okay, I thought about this too.

Okay,
So now I removed the package by this
```
npm uninstall -g falak
```

And install it again
```
$ npm install -g falak
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/flk -> /usr/local/lib/node_modules/falak/framework/bin/flk

> node-sass@4.13.0 install /usr/local/lib/node_modules/falak/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/ahmed/.npm/node-sass/4.13.0/darwin-x64-72_binding.node

> core-js@2.6.11 postinstall /usr/local/lib/node_modules/falak/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> node-sass@4.13.0 postinstall /usr/local/lib/node_modules/falak/node_modules/node-sass
> node scripts/build.js

Binary found at /usr/local/lib/node_modules/falak/node_modules/node-sass/vendor/darwin-x64-72/binding.node
Testing binary
Binary is fine
+ falak@1.3.0
added 543 packages from 307 contributors in 29.616s
```

Now when I create new project, I feel like nothing happened.
```
$ flk new blog
Creating blog workspace...
```

When I check what's created in the current directory
```
$ tree -L 1 blog/
blog/
└── package.json

0 directories, 1 file
```

And that's its content
```
$ cat blog/package.json
{
  "name": "blog",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

So 😅

**Comment by devahmedshendy** [comment]
@hassanzohdy 
Hmm, just to share this if matters.
I tried installing it using **sudo**, but the error was weird this time, I am sure nothing related to the project, but thought to share it anyway, maybe something broken in my system.

```
$ sudo npm install -g falak
Password:
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/flk -> /usr/local/lib/node_modules/falak/framework/bin/flk

> node-sass@4.13.0 install /usr/local/lib/node_modules/falak/node_modules/node-sass
> node scripts/install.js

sh: node: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! node-sass@4.13.0 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@4.13.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ahmed/.npm/_logs/2019-12-31T14_55_53_311Z-debug.log
```

**Comment by hassanzohdy** [comment]
OK i've checked it now to make a full working application, and it seems now to me it's working just fine.

Reinstall it again and you should be fine.

Sorry for the buggy bugs you issued.

Also let me know how it went with you with the creating application process.

Regarding the sudo command, probably it's because of [Node Sass Binary Installation](https://github.com/sass/node-sass), but the framework will "hopefully" handle that mater for you.

**Comment by devahmedshendy** [comment]
It's okay for bugs.

And yes, it works now 👍.
